# ResearchEquals Cohorts

:::{.callout-tip}
We regularly run cohorts - [check out our Tito page](https://ti.to/libscie) to see when and get your spot!
:::

This is the instructor guide for our ResearchEquals Cohorts. We iterate over create - so here's all you need right now to get started and run your own cohort, in case you want.

<details>
    <summary>Cohort onboarding</summary>

- Welcome [00:00 - 00:15]
    - Welcome on this journey of publishing your research differently [00:00 - 00:03]
        - We will be discovering how to publish your research differently, and how to curate research differently.
        - This is a safe space to learn, so I encourage questions and feedback, no matter how obvious it might feel.
    - This session will be recorded! 🔴
    - Short intro instructor [00:03-00:05]
        - I’m Chris Hartgerink, founder of ResearchEquals and a researcher myself. I did my PhD in statistics, and am happy to now be working on sustainable alternatives in research that make our lives easier.
        - ResearchEquals is one such project and I am thankful that you lot are making the time to join here!
- Goals [00:05 - 00:07]
    - The goal of the cohort is provide a safe learning environment around modular publishing. What is it? Why is it? How does it work?
    - Together we’ll learn how to publish the research process instead of the results alone
    - We’re also here, together, to create connection and community, so we don’t have to go at it alone.
- Code of Conduct [00:07 - 00:10 - Vinodh Ilangovan]
- Structure [00:10 - 00:15]
    - Mon - Thu
    - Meet in Zoom
    - Chat in Discord
    - There may be additional materials before the cohort calls for you to go through, which we’ll always keep time effective.
    - At the end of the cohort, everybody who completed the course will receive a digital certificate.
- Short introductions [00:15 - 00:30 - Chris]
    - Getting the hang of whiteboards
        - Where is everyone from
    - Introduce yourself
        - ~2min each
            - Who are you
            - Research interest
            - What’s your guilty pleasure
        - Others make sticky notes
    - To make an account on ResearchEquals if they haven’t already
    - Getting the hang of Discord [00:30 - 00:35 - Chris]
- Closing
    - On Thursday, same time, we will discuss modules in-depth, and

</details>

<details>
    <summary>Why and what are modules?</summary>

- Welcome
    - [Icebreaker]
    - Recap
        - In our first call, we got to know each other a bit.
        - For this call, you prepared by watching a short video on the idea of publishing the research process. You learned about selective publishing, and how altering predictions based on results may be a result from the article format.
        - You now know that research modules are comparable to research steps.
    - Today's goal: Understand single modules and what goes into a module.
- Do you feel like published research in your field showcases the way research is actually done?
    - Where could it improve?
- What research steps are often overlooked in your field?
- Demo ResearchEquals
- Exercise
    - [ ] Think about your most recent research project. What is the latest step you took? What are the outputs/files you created from this?
    - [ ] Create your own draft module
    - [ ] Go through the module types - are there any steps you are already missing?
- Reportback from exercise
    - What's your first impressions of research modules?
- Recap of today
    - We learned how to create our first module, and what has to be included for each module.
    - We also learned what optional information 
- Today we learned about individual steps in the research process. 
    - Next time we'll talk more about how those steps combine into an entire research journey. 
    - For the next call, take a few minutes to write down the steps involved in your research. 
</details>



<details>
    <summary>Deconstructing your research</summary>

- Welcome [5min]
    - [Icebreaker]
    - Recap - we learned about singular modules last call
    - Today we'll learn how all these modules tie together to create different research processes
- Shareback: reflections on your own research journey [5min]
    - What steps surprised you?
    - What would you like your research journey to include, but currently do not?
    - Where do you think your research is different from fields?
- Exercise 1: Match the research process to the study type [5 min]
- Discussion: What's the added value in sharing the research journey? [10min]
- Exercise 2: Whiteboarding your research as a process [10min]
    - What's the first step in a research process?
    - What's the last step in a research process?
    - Add other steps, before or after the ones already there
- Discussion: Where would your presentations fit into this entire process?
- Next call
- Exercise 3: What are the three most recent research steps you've taken?
    - Prepare drafts for each step (include the files, title, description)
</details>


<details>
    <summary>Publishing your first module(s)</summary>

- Welcome
    - [Icebreaker]
    - Last call, we worked on deconstructing the research process.
    - Today is about applying that knowledge to your own work
- Showcase: What were your three most recent research steps?
- Demo: How to link modules
    - Link to previous work outside of ResearchEquals
    - Why can we only link once previous work is published?
- Exercise: Link and publish your three prepared modules
- Demo the graph
- Planning the next three steps
- Next call...
    - ...is on how to collaborate
    - Think about what's important to you?
        - What are examples of good collaborators?
        - What are examples of bad collaborators?

</details>

<details>
    <summary>Kind collaboration</summary>

- Welcome
    - [Icebreaker]
- Reportback: Good/bad collaboration experiences
- Exercise: Values for good collaboration
- Demo: ResearchEquals collaboration sequence
    - Create a draft module
    - Invite others present
    - Accept invitation
    - Approve for publication
- 
- Next call...
    - We'll have a guest!
    - In the final content call, we'll learn how to curate research
    - We've talked much about publishing your work, but we all do curation as well
    - For next time, take ten minutes to reflect on what curation you already do (whether that's reading lists, controversial topics, topic deepdives, or anything else!)
</details>
 

<details>
    <summary>Curating research</summary>

- Welcome
    - [Icebreaker]
- Reportback: Where do you already curate research?
- Guest talk: What does curation mean to you?
- What is the current state of curation?
    - Overlay journals intro
    - How many overlay journals exist
    - Journals as communities
- Demo collections ResearchEquals
- Exercise: Create your own collection, play around, and share any feedback, thoughts or questions
- Next call

</details>

<details>
    <summary>Cohort graduation</summary>


- Welcome
    - [Icebreaker]
- Final evaluation 
- Congratulate the cohort members
- Celebrate by playing games in Discord lounge

</details>

## Icebreaker questions

- What is one of your guilty pleasures?
- What movie have you seen multiple times?
- What is a classic movie you only saw until much later?
- What vegetable would you be? (vegetable or fruit discussions aside)
- What’s something on your desk, a nearby wall, or out the window that cheers you up during the day?
- What’s a common word or phrase that you don’t like/won’t use?
- What is the most recent book you read? Did you like it?

## Virtual teaching "tricks"

- Let people raise their hand in Zoom whenever they're done with an exercise,