# Vacation policy

[Vacation days template](https://www.notion.so/Vacation-days-template-13e7d39d312f40b383415058222bd4e5)

# Policy

<aside>
💡 German employment law is rather complex and different regulations can apply for different conditions that might not be fully covered in this document. If you have any questions or concerns, please always feel free to ask your manager about your specific case.

</aside>

### Internal policy

- The maximum vacation days is 36 per year (= 288 hours) if you work the full year at 1FTE. If you started during the year the number of days is proportional and probably mentioned in your contract.
- Every internal employee has a protected page shared only your managers, where the vacation days can be tracked.  You have to manually input the number of vacation days taken. One vacation day equals 8 hours. One week off equals 32 hours (4 full work days with 8 hours each). The spreadsheet immediately shows how much you've taken already.
- 1-2 days of leave can be taken without approval if there are no deadlines that are affected (please talk to your team members first about this), but need to be registered.
- Longer leave can be taken in consultation with your team members and manager. If unclear on who your manager is, consult your manager.

---

### In addition to our internal policies, there are also some legal requirements:

- As an employer we have to make sure that you take at least four non-consecutive weeks off during the year. Also, one of the vacations you request need to be at least 12 consecutive working days.
- If you get sick while on vacation, please make sure to get a medical certificate for the respective period on the first day of your illness and you get your approved vacation days back. In this case, you must communicate the address you're staying at to your manager (SMS, WiFi, or postage costs will be covered by Liberate Science).
- Please make sure to use your vacation days during each calendar year as your vacation days expire at the end of the respective year. If you are unable to use your vacation days for operational or personal reasons (e.g. health, maternity protection or parental leave), you can still use them within the first three months of the next year (i.e. until March 31).